version: '2'

services:

  source-ingest-pe2:
    image: 131.137.160.79:9191/gciplus-microservices/gen3/decode-pe2:1.0.0
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}-decodeais
      LOGGING_LEVEL: ${logging_level}
      NUM_STREAM_THREADS: ${num_stream_threads}
      AUTO_OFFSET_RESET: ${auto_offset_reset}
      BOOTSTRAP_SERVERS_CONFIG: ${kafka_host}:${kafka_port}
      SCHEMA_REGISTRY_URL: ${schema_registry_url}
      SCHEMA_REGISTRY_SECURE_URL: ${schema_registry_secure_url}
      KAFKA_INPUT_TOPICS: ${kafka_input_topics}
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic}
      MONITORING_HEALTHCHECK_PORT: 9000
      MONITORING_HEALTHCHECK_PATH: healthcheck
      MONITORING_HEALTHCHECK_REFRESH_MS: 30000
      MONITORING_PROMETHEUS_PORT: 9001
    external_links:
      - ${kafka_service}:kafka
      - ${schema_registry_service}:schema-registry
    labels:
      prometheus.port: 9001
