version: '2'
services:
  kafka-mirrormaker:
    scale: 1

catalog:
  name: "kafka-mirrormaker"
  version: "development"
  description: "A customized packaging of Kafka Mirrormaker that is used to sync data between Kafka Brokers. This image is packaged with a customized message handler that will allow for renaming topics, and synch of the special '_schemas' that will rewrite the schemas with the modified topic name if required."
  minimum_rancher_version: v0.51.0
  upgrade_from: none
  questions:
    - variable: application_id
      label: "Application ID"
      required: true
      type: "string"
      description: "A unique string (with no spaces) that identifies this applicationstring." 
    - variable: kafka_service         
      description: "Kafka Stack/Service."
      label: "Kafka Broker to Connect to."                             
      required: false
      type: "service"
    - variable: source_kafka_host 
      label: "Kafka Broker Host (Source)"
      required: true
      type: "string"
    - variable: source_kafka_port 
      label: "Kafka Broker Port (Source)"
      required: true
      type: "int"
      default: "9092"
    - variable: target_kafka_host 
      label: "Kafka Broker Host (Target)"
      required: true
      type: "string"
    - variable: target_kafka_port 
      label: "Kafka Broker Port (Target)"
      required: true
      type: "int"
      default: "9092"
    - variable: source_consumer_groupid
      label: "Source Consumer Group ID"
      required: true
      type: "string"
    - variable: kafka_topic_whitelist
      label: "Comma seperated list of kafka topics to consume."
      required: true
      type: "string"
    - variable: auto_offset_reset
      label: "Auto Offset Reset"
      required: true
      type: "enum"
      default: "earliest"
      options:
        - "earliest"
        - "latest"
      description: "Consume data from beginning of topic (earliest) or from now onward (latest). (* If mirroring avro data (the _schemas topic), earliest is reccomended."
    - variable: num_streams
      label: "Number of Streams"
      required: true
      type: "int"
      default: "1"
      description: "Number of consumption streams."
    - variable: offset_commit_interval_ms
      label: "Offset Commit Interval (Milliseconds)"
      required: true
      type: "int"
      default: "60000"
    - variable: message_handler
      label: "Message Handler"
      required: false
      type: "string"
      description: "The default RenameTopicHandler is used to change the name of a kafka topic on the destination broker. If this is to be used, 'Message Handler Args' must also be set appropiately."
      default: "ca.forces.marlant.bis.gciplus.common.core.kafka.extensions.mirrormaker.RenameTopicHandler"
    - variable: message_handler_args
      label: "Message Handler Args"
      required: false
      type: "string"
      description: "A semicolon separated list of string pairs, which are itself separated by a comma. (Ie. sourcetopic1,targettopic1;sourcetopic2,targettopic2;...) In this example, any message from the topic sourcetopic1 would be mirrored to targettopic1 (and the same with 2) on the target cluster. Any other topics that MirrorMaker is following will not be changed and written to a topic of the same name on the target cluster. This must be configured is using the RenameTopicHandler."
