version: '2'
services:

  kafka-mirrormaker:
    image: 131.137.160.79:9191/gciplus-microservices/common/confluent-kafka-utils:1.0.0
    environment:
      APPLICATION_ID: ${application_id}-mirrormaker
      MONITORING_PROMETHEUS_PORT: 9001
    restart: on-failure
    external_links:
      - ${kafka_service}:kafka
    command: bash -c "./bin/kafka-mirror-maker --consumer.config <(echo -e 'bootstrap.servers=${source_kafka_host}:${source_kafka_port}\\ngroup.id=${source_consumer_groupid}\\nauto.offset.reset=${auto_offset_reset}') --producer.config <(echo -e 'bootstrap.servers=${target_kafka_host}:${target_kafka_port}') --num.streams ${num_streams} --offset.commit.interval.ms ${offset_commit_interval_ms} --message.handler ${message_handler} --message.handler.args '${message_handler_args}' --whitelist '${kafka_topic_whitelist}'"
    labels:
      prometheus.port: 9001

