version: '2'
services: 
  encode-otg:
    image: 131.137.160.79:9191/gciplus-microservices/gen3/encode-otg:1.0.1
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}-encodeotg
      LOGGING_LEVEL: ${logging_level}
      NUM_STREAM_THREADS: ${num_stream_threads}
      AUTO_OFFSET_RESET: ${auto_offset_reset}
      BOOTSTRAP_SERVERS_CONFIG: ${kafka_host}:${kafka_port}
      SCHEMA_REGISTRY_URL: ${schema_registry_url}
      KAFKA_INPUT_TOPICS: ${kafka_input_topics_maritimecontact}
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic_avrootg}
      KAFKA_COMPRESSION: snappy
      MAX_NUMBER_OF_CONTACTS_ PER_AGGREGATION: ${max_contacts_per_otg}
      RYTHM_ENGINE_PROPERTIES_PATH: "/opt/gciplus/encode-otg/rythm-engine.properties"
      COMMIT_INTERVAL_MS_CONFIG: 1000
      AGGREGATION_TIME_WINDOW_MS: 1000
      MARITIME_CONTACT_TO_XCTC_BINDING_TTL_IN_MILLIS: 1000
      JAVA_OPTS: "-Xms64m -Xmx640m"
      PARSE_RUNNER_RECOVERY_MAX_ATTEMPTS: 25
      MONITORING_HEALTHCHECK_PORT: 9000
      MONITORING_HEALTHCHECK_PATH: healthcheck
      MONITORING_HEALTHCHECK_REFRESH_MS: 30000
      MONITORING_PROMETHEUS_PORT: 9001
    external_links:
      - ${kafka_service}:kafka
      - ${schema_registry_service}:schema-registry
    labels:
      prometheus.port: 9001

  encode-acp128:
    image: 131.137.160.79:9191/gciplus-microservices/gen3/encode-acp128:1.0.1
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}-encodeacp128
      LOGGING_LEVEL: ${logging_level}
      NUM_STREAM_THREADS: ${num_stream_threads}
      AUTO_OFFSET_RESET: ${auto_offset_reset}
      BOOTSTRAP_SERVERS_CONFIG: ${kafka_host}:${kafka_port}
      SCHEMA_REGISTRY_URL: ${schema_registry_url}
      KAFKA_INPUT_TOPICS: ${kafka_output_topic_avrootg}
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic_textacp128otg}
      KAFKA_COMPRESSION: snappy
      MAX_NUMBER_OF_CONTACTS_PER_AGGREGATION: ${max_contacts_per_otg}
      RYTHM_ENGINE_PROPERTIES_PATH: "/opt/gciplus/encode-acp128/rythm-engine.properties"
      PREFER_ENVELOPE_VALUES: ${prefer_envelope_values}
      SECURITY_RELEASE_CODE: ${security_release_code}
      SECURITY_WARNING_SIGNALS: ${security_warning_signals}
      ORIGINATOR: ${originator}
      ACTION_ADDRESSEE: ${action_addressee}
      CLASSIFICATION: ${classification}
      JAVA_OPTS: "-Xms64m -Xmx640m"
      PARSE_RUNNER_RECOVERY_MAX_ATTEMPTS: 25
      MONITORING_HEALTHCHECK_PORT: 9000
      MONITORING_HEALTHCHECK_PATH: healthcheck
      MONITORING_HEALTHCHECK_REFRESH_MS: 30000
      MONITORING_PROMETHEUS_PORT: 9001
    external_links:
      - ${kafka_service}:kafka
      - ${schema_registry_service}:schema-registry
    labels:
      prometheus.port: 9001
