version: '2'
services:
  maritimecontact-geodecimator:
    image: 131.137.160.79:9191/gciplus-microservices/gen3/maritimecontact-geodecimator:1.0.2
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}-geodecimate
      BOOTSTRAP_SERVERS_CONFIG: ${bootstap_servers_config} 
      SCHEMA_REGISTRY_URL: ${schema_registry_url}
      KAFKA_INPUT_TOPICS: ${kafka_input_topics}
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic_decimated}
      GEODECIMATOR_WINDOW_MS: ${geodecimator_window_ms}
      GEODECIMATOR_EXPIRY_MS: ${geodecimator_expiry_ms}
      GEODECIMATOR_POLYGON: ${geodecimator_polygon}
      GEODECIMATOR_AGGREGATION_FIELDS: "Name,Mmsi,Imo,Callsign,Metadata.Provider"
      GEODECIMATOR_GEOHASH_LENGTH: 3
      NUM_STREAM_THREADS: ${num_stream_threads}
      NUM_SEGMENTS: 20
      AUTO_OFFSET_RESET: ${auto_offset_reset}
      FUTURE_CONTACT_TOLERANCE_MS: 600000
      MONITORING_HEALTHCHECK_PORT: 9000
      MONITORING_HEALTHCHECK_PATH: healthcheck
      MONITORING_HEALTHCHECK_REFRESH_MS: 30000
      MONITORING_PROMETHEUS_PORT: 9001
      LOGGING_LEVEL: ${logging_level}
      JAVA_OPTS: "-Xms512m -Xmx1g"
    external_links:
      - ${kafka_service}:kafka
      - ${schema_registry_service}:schema-registry
    labels:
      prometheus.port: 9001

  enforce-schema-compatibility:
    image: 131.137.160.79:9191/gciplus-microservices/gen3/enforce-schema-compatibility:1.0.2
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}-enforceschema
      BOOTSTRAP_SERVERS_CONFIG: ${bootstap_servers_config} 
      SCHEMA_REGISTRY_URL: ${schema_registry_url}
      KAFKA_INPUT_TOPICS: ${kafka_output_topic_decimated}
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic_schema_enforced}
      NUM_STREAM_THREADS: ${num_stream_threads}
      AUTO_OFFSET_RESET: ${auto_offset_reset}
      MONITORING_HEALTHCHECK_PORT: 9000
      MONITORING_HEALTHCHECK_PATH: healthcheck
      MONITORING_HEALTHCHECK_REFRESH_MS: 30000
      MONITORING_PROMETHEUS_PORT: 9001
      LOGGING_LEVEL: ${logging_level}
      JAVA_OPTS: "-Xms64m -Xmx256m"
    external_links:
      - ${kafka_service}:kafka
      - ${schema_registry_service}:schema-registry
    labels:
      prometheus.port: 9001
