version: '2'
services:

  ingest-socket:
    image: 131.137.160.79:9191/gciplus-microservices/common/ingest-socket:4.1.0
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}-ingestsocket
      LOGGING_LEVEL: ${logging_level}
      INPUT_URI: ${input_uri}
      INPUT_SOCKET_HOST: ${input_socket_host}
      INPUT_SOCKET_PORT: ${input_socket_port}
      INPUT_SOCKET_SYNC: false
      INPUT_SOCKET_CLIENT_MODE_ENABLED: ${client_mode}
      INPUT_SOCKET_PROTOCOL_UDP: false
      INPUT_SOCKET_MULTICAST_OVER_UDP: false
      TEXTLINE: true
      REPLACEMENT_CHARACTER_ENABLED: false
      KAFKA_HOST: ${kafka_host}
      KAFKA_PORT: ${kafka_port} 
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic_rawais}
      KAFKA_COMPRESSION: snappy
      JMX_AGENT_PORT: 11083
      SEDA_SIZE: 50000
      SEDA_CONCURRENT_CONSUMERS: 1
      JAVA_OPTS: "-Xms64m -Xmx640m -Dlog4j.configurationFile=log4j2.properties -javaagent:lib/jmx_prometheus_javaagent-0.10.jar=9001:config.yml"
      MONITORING_HEALTHCHECK_PORT: 9000
      MONITORING_HEALTHCHECK_PATH: healthcheck
      MONITORING_HEALTHCHECK_REFRESH_MS: 30000
  
    external_links:
      - ${kafka_service}:kafka
    labels:
      prometheus.port: 9001

  decode-mssis:
    image: 131.137.160.79:9191/gciplus-microservices/gen3/decode-mssis:2.0.2
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}-decodemssis
      AUTO_OFFSET_RESET: ${auto_offset_reset}
      RELEASABILITY: "ALL"
      PROVIDER: ${provider}
      ORIGINAL_MESSAGE_FORMAT: ais
      ORIGINAL_ENVELOPE_FORMAT: mssis
      CLASSIFICATION: "U N C L A S S I F I E D"
      LOGGING_LEVEL: ${logging_level}
      KAFKA_HOST: ${kafka_host}
      KAFKA_PORT: ${kafka_port}
      KAFKA_INPUT_TOPIC: ${kafka_output_topic_rawais}
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic_avrorawais}
      KAFKA_COMPRESSION: snappy
      KAFKA_SERIALIZER_SETTINGS: "schema.registry.url=${schema_registry_url}"
      JMX_AGENT_PORT: 11083
      SEDA_SIZE: 50000
      JAVA_OPTS: "-Xms64m -Xmx640m -Dlog4j.configurationFile=log4j2.properties -javaagent:lib/jmx_prometheus_javaagent-0.10.jar=9001:config.yml"
      MONITORING_HEALTHCHECK_PORT: 9000
      MONITORING_HEALTHCHECK_PATH: healthcheck
      MONITORING_HEALTHCHECK_REFRESH_MS: 30000
  
    external_links:
      - ${kafka_service}:kafka
      - ${schema_registry_service}:schema-registry
    labels:
      prometheus.port: 9001

  decode-ais:
    image: 131.137.160.79:9191/gciplus-microservices/gen3/decode-ais:3.1.0
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}-decodeais
      LOGGING_LEVEL: ${logging_level}
      NUM_STREAM_THREADS: ${num_stream_threads}
      AUTO_OFFSET_RESET: ${auto_offset_reset}
      BOOTSTRAP_SERVERS_CONFIG: ${kafka_host}:${kafka_port}
      SCHEMA_REGISTRY_URL: ${schema_registry_url}
      KAFKA_INPUT_TOPICS: ${kafka_output_topic_avrorawais}
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic_avromaritimecontact}
      KAFKA_OUTPUT_TOPIC_AISCONTACTS: ${kafka_output_topic_avroaismaritimecontact}
      FILTER_ZEROED_POSITIONS: ${filter_zeroed_positions}
      KAFKA_COMPRESSION: snappy
      JAVA_OPTS: "-Xms64m -Xmx640m -Dlog4j.configurationFile=log4j2.properties"
      PARSE_RUNNER_RECOVERY_MAX_ATTEMPTS: 25
      MONITORING_HEALTHCHECK_PORT: 9000
      MONITORING_HEALTHCHECK_PATH: healthcheck
      MONITORING_HEALTHCHECK_REFRESH_MS: 30000
      MONITORING_PROMETHEUS_PORT: 9001
  
    external_links:
      - ${kafka_service}:kafka
      - ${schema_registry_service}:schema-registry
    labels:
      prometheus.port: 9001
