node-exporter:
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  image: prom/node-exporter:latest
  stdin_open: true

prom-conf:
    tty: true
    image: 131.137.160.79:9191/gciplus-microservices/common/prom-conf:development
    volumes:
      - /etc/prom-conf/
      - /var/prom-rancher-sd-data:/prom-rancher-sd-data
    net: none

prometheus:
    tty: true
    image: prom/prometheus:v2.1.0
    command: --config.file=/etc/prom-conf/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles
    ports:
      - 9090:9090
    labels:
      io.rancher.sidekicks: prom-conf
    volumes_from:
      - prom-conf
    volumes:
      - prometheus-data:/prometheus
    volume_driver: ${VOLUME_DRIVER}
    links:
    - node-exporter:node-exporter
    - prometheus-rancher-exporter:prometheus-rancher-exporter
    extra_hosts:
    - "rancher-server:${RANCHER_SERVER}"

influxdb:
    tty: true
    image: influxdb:1.7.4
    ports:
      - 8086
    environment:
      INFLUXDB_DATA_MAX_VALUES_PER_TAG: 0


grafana:
    tty: true
    image: grafana/grafana:6.0.2
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus
      - influxdb:influxdb
      - prometheus-rancher-exporter:prometheus-rancher-exporter

prometheus-rancher-exporter:
    tty: true
    labels:
      io.rancher.container.create_agent: true
      io.rancher.container.agent.role: environment
    image: infinityworks/prometheus-rancher-exporter:v0.22.52

prometheus-rancher-discovery:
    tty: true
    image: 131.137.160.79:9191/gciplus-microservices/common/prometheus-rancher-discovery:1.0.0
    volumes:
      - /var/prom-rancher-sd-data:/prom-rancher-sd-data

