version: '2'

services:
  ssms-vessel-api:
    scale: 1
    start_on_create: true
  ssms-flight-api:
    scale: 1
    start_on_create: true
  postgrest:
    scale: 1
    start_on_create: true
  openresty:
    scale: 1
    start_on_create: true
  ssms-api:
    scale: 1
    start_on_create: true
  db:
    scale: 1
    start_on_create: true
  swagger:
    scale: 1
    start_on_create: true
catalog:
  name: "ssms-api"
  version: "development"
  description: "Provides flight, vessel and registry api endpoints for the SSMS project."
  minimum_rancher_version: v0.51.0
  upgrade_from: none
  questions:
    - variable: BASE_PATH
      label: "Base Path"
      required: true
      type: "string"
      default: "/SSMS-API"
      description: "Base Path"
    - variable: DEVELOPMENT
      label: "Developent environment"
      required: true
      type: "int"
      default: "0"
      description: "Developent environment"
    - variable: DB_PORT
      label: "DB Port"
      required: true
      type: "int"
      default: "5432"
      description: "Database port"
    - variable: DB_POOL
      label: "DB Connection Pool"
      required: true
      type: "int"
      default: "10"
      description: "DB Connection Pool"
    - variable: DB_HOST
      label: "DB Host"
      required: true
      type: "string"
      default: "db"
      description: "Database host name"
    - variable: DB_NAME
      label: "DB Name"
      required: true
      type: "string"
      default: "ssms"
      description: "Database name"
    - variable: DB_SCHEMA
      label: "DB Schema"
      required: true
      type: "string"
      default: "api"
      description: "Database Schema for postgrest"
    - variable: JWT_SECRET
      label: "JWT Secret"
      required: true
      type: "string"
      default: "KSQgCwAtcJwlmb7bhzmCTrt0Um6muukY"
      description: JWT Secret"
    - variable: DB_ANON_ROLE
      label: "Anonymous user role"
      required: true
      type: "string"
      default: "anonymous"
      description: "Name of the role for anonymous database user"
    - variable: SUPER_USER
      label: "Superuser"
      required: true
      type: "string"
      default: "superuser"
      description: "Name of the account that will manage the database"
    - variable: SUPER_USER_PASSWORD
      label: "Superuser Password"
      required: true
      type: "password"
      description: "Password for the account that will manage the database"
      default: "superuserpass"
    - variable: DB_USER
      label: "Database user name"
      required: true
      type: "string"
      default: "authenticator"
      description: "Name of the account that will manage authentication to the database"
    - variable: DB_PASS
      label: "Database User Password"
      required: true
      type: "password"
      description: "Password for the account that will manage authentication to the database"
      default: "authenticatorpass"
    - variable: RABBITMQ_DEFAULT_USER
      label: "RabbitMQ user name"
      required: true
      type: "string"
      default: "admin"
      description: "Name of the account that will manage authentication to the database"
    - variable: RABBITMQ_DEFAULT_PASS
      label: "RabbitMQ User Password"
      required: true
      type: "password"
      description: "Password for the account that will manage authentication to the database"
      default: "adminpass"
    - variable: SERVER_PROXY_URI
      label: "Proxy URI"
      description: "Proxy URI"   
      required: true
      type: "string"
      default: "http://0.0.0.0:8087/rest/"
     

# GEOSERVER_PASSWORD=X4VWiT3f

    - variable: GEOSERVER_HOST
      label: "Geoserver Host"         
      description: "Geoserver Host"                                   
      required: true
      type: "string"
      default: "https://gpw.canmarnet.gc.ca/BETA-GEO/"                        
    - variable: GEOSERVER_USER
      label: "Geoserver Username"         
      description: "Geoserver Username"                                   
      required: true
      type: "string"
      default: "ssms"
    - variable: GEOSERVER_PASSWORD
      label: "Geoserver Password"         
      description: "Geoserver Password"                                   
      required: true
      type: "password"
      default: "ssms"
    - variable: MERGED_API_PORT
      description: "Service access port on the host port that maps to container port 3030"
      label: "Merged API Port"
      required: true
      type: "int"
      default: "3039"
    - variable: VESSEL_API_PORT
      description: "Service access port on the host port that maps to container port 3030"
      label: "Vessel API Port"
      required: true
      type: "int"
      default: "3036"
    - variable: FLIGHT_API_PORT 
      description: "Service access port on the host port that maps to container port 3030"
      label: "Flight API Port"
      required: true
      type: "int"
      default: "3037"
    - variable: OPENRESTY_PORT
      description: "Service access port on the host port that maps to container port"
      label: "OpenResty Port"
      required: true
      type: "int"
      default: "8087"
    - variable: POSTGREST_HOST
      description: "Service access"
      label: "Postgrest Host"
      required: true
      type: "string"
      default: "postgrest"
    - variable: POSTGREST_PORT
      description: "Service access port on the host port that maps to container port 3000"
      label: "Postgrest Port"
      required: true
      type: "int"
      default: "3000"
