version: '2'
services:
  vessel-identity-service:
    scale: 1
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 9000
      unhealthy_threshold: 3
      initializing_timeout: 120000
      interval: 30000
      strategy: recreate
      request_line: GET "/healthcheck" "HTTP/1.0"
      reinitializing_timeout: 120000
  elastic-search:
    scale: 1
  identity-data:
    scale: 1

catalog:
  name: "vessel-identity"
  version: "1.0.0"
  description: "Provides vessel/ship identity details backed by a Elasticsearch DB."
  minimum_rancher_version: v0.51.0
  upgrade_from: none
  questions:
    - variable: application_id
      label: "Application Id"
      required: true
      type: "string"
      description: "An alphanumeric string that uniquely identifies this application instance."
    - variable: logging_level
      label: "Logging Level"
      description: "See Log4J documentation for further explanation of these levels."   
      required: true
      type: "enum"
      options:
        - all
        - debug
        - info
        - warn
        - error
        - fatal
        - trace
      default: "info"
    - variable: seda_concurrent_consumers
      label: "SEDA Concurrent Consumers"         
      description: "Camel SEDA Concurrent Consumers"                                   
      required: true
      type: "string"
      default: "3"            
    - variable: identity_host
      label: "Identity Host"         
      description: "Host of this service(name/ip)."                                   
      required: true
      type: "string"
      default: "0.0.0.0"
    - variable: identity_port
      description: "Service access port on the host port that maps to container port 8080"
      label: "Identity Port"
      required: true
      type: "int"
      default: "8080"
    - variable: elastic_index_name 
      label: "Elasticsearch Document Index Name"
      required: true
      type: "string"
      default: "vessel_merged"
    - variable: data_file
      description: "File that contains vessel data in csv format " 
      label: "Data File Name "
      required: true
      type: "string"
      default: "vessel"