version: '2'
services:

  ingest-socket:
    image: 131.137.160.79:9191/gciplus-microservices/common/ingest-socket:development
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}-ingestsocket
      LOGGING_LEVEL: ${logging_level}
      INPUT_URI: ${input_uri}
      INPUT_SOCKET_HOST: ${input_socket_host}
      INPUT_SOCKET_PORT: ${input_socket_port}
      INPUT_SOCKET_CLIENT_MODE_ENABLED: ${client_mode}
      TEXTLINE: true
      REPLACEMENT_CHARACTER_ENABLED: false
      BYTE_FILTERING_ENABLED: false
      KAFKA_HOST: ${kafka_host}
      KAFKA_PORT: ${kafka_port}
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic_rawais}
      SEDA_CONCURRENT_CONSUMERS: 1
      USE_CLASSPATH_RESOURCE_CAMEL_PROPERTIES: true
      MONITORING_HEALTHCHECK_INACTIVITY_TIMEOUT_MS: 300000
    external_links:
      - ${kafka_service}:kafka
    labels:
      prometheus.port: 9001

  decode-nmea:
    image: 131.137.160.79:9191/gciplus-microservices/gen3/decode-nmea:development
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}-decodenmea
      RELEASABILITY: "ALL"
      PROVIDER: ${provider}
      LOGGING_LEVEL: ${logging_level}
      KAFKA_HOST: ${kafka_host}
      KAFKA_PORT: ${kafka_port}
      KAFKA_INPUT_TOPIC: ${kafka_output_topic_rawais}
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic_avrorawais}
      KAFKA_SERIALIZER_SETTINGS: "schema.registry.url=${schema_registry_url}"
    external_links:
      - ${kafka_service}:kafka
      - ${schema_registry_service}:schema-registry
    labels:
      prometheus.port: 9001

  decode-ais:
    image: 131.137.160.79:9191/gciplus-microservices/gen3/decode-ais:development
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}-decodeais
      LOGGING_LEVEL: ${logging_level}
      NUM_STREAM_THREADS: ${num_stream_threads}
      AUTO_OFFSET_RESET: ${auto_offset_reset}
      BOOTSTRAP_SERVERS_CONFIG: ${kafka_host}:${kafka_port}
      SCHEMA_REGISTRY_URL: ${schema_registry_url}
      KAFKA_INPUT_TOPICS: ${kafka_output_topic_avrorawais}
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic_avromaritimecontact}
      KAFKA_OUTPUT_TOPIC_AISCONTACTS: ${kafka_output_topic_avroaismaritimecontact}
      FILTER_ZEROED_POSITIONS: ${filter_zeroed_positions}
    external_links:
      - ${kafka_service}:kafka
      - ${schema_registry_service}:schema-registry
    labels:
      prometheus.port: 9001
