version: '2'
services:
  source-ingest-pal:
    image: 131.137.160.79:9191/gciplus-microservices/gen3/ingest-pal:1.0.5
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}
      LOGGING_LEVEL: ${logging_level}
      KAFKA_HOST: ${kafka_host}
      KAFKA_PORT: ${kafka_port} 
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic}
      KAFKA_AIS_OUTPUT_TOPIC: ${kafka_ais_output_topic}
      KAFKA_EDT_VESSEL_OUTPUT_TOPIC: ${kafka_edt_vessel_output_topic}
      KAFKA_EDT_ANIMAL_OUTPUT_TOPIC: ${kafka_edt_animal_output_topic} 
      KAFKA_EDT_ICEBERG_OUTPUT_TOPIC: ${kafka_edt_iceberg_output_topic}
      KAFKA_EDT_PACKICE_OUTPUT_TOPIC: ${kafka_edt_packice_output_topic}
      KAFKA_EDT_BUOY_OUTPUT_TOPIC: ${kafka_edt_buoy_output_topic}
      KAFKA_EDT_GEAR_OUTPUT_TOPIC: ${kafka_edt_gear_output_topic}
      KAFKA_EDT_OTHER_OUTPUT_TOPIC: ${kafka_edt_other_output_topic}
      KAFKA_NAV_OTHER_OUTPUT_TOPIC: ${kafka_nav_other_output_topic}
      KAFKA_GEN_ANIMAL_OUTPUT_TOPIC: ${kafka_gen_animal_output_topic}
      KAFKA_GEN_ICEBERG_OUTPUT_TOPIC: ${kafka_gen_iceberg_output_topic}
      KAFKA_GEN_PACKICE_OUTPUT_TOPIC: ${kafka_gen_packice_output_topic}
      KAFKA_GEN_BUOY_OUTPUT_TOPIC: ${kafka_gen_buoy_output_topic}
      KAFKA_GEN_GEAR_OUTPUT_TOPIC: ${kafka_gen_gear_output_topic}
      KAFKA_GEN_OTHER_OUTPUT_TOPIC: ${kafka_gen_other_output_topic}
      KAFKA_COMPRESSION: snappy
      KAFKA_SERIALIZER_SETTINGS: "schema.registry.url=${schema_registry_url}"
      KAFKA_SERIALIZER_CLASS: ca.forces.marlant.bis.gciplus.common.core.camel.kafka.EnvConfKafkaAvroSerializer
      JMX_AGENT_PORT: 11083
      SEDA_CONCURRENT_CONSUMERS: 4
      PAL_ENDPOINT: ${pal_endpoint}
      PAL_ENDPOINT_ADDRESS: ${pal_endpoint_address}
      PAL_WSDL_ADDRESS: ${pal_wsdl_address}
      PAL_USERNAME: ${pal_username}
      PAL_PASSWORD: ${pal_password}
      PAL_CRON_SCHED: ${pal_cron_sched}
      JAVA_OPTS: "-Xms64m -Xmx640m -javaagent:lib/jmx_prometheus_javaagent-0.10.jar=9001:config.yml -Dlog4j.configurationFile=log4j2.properties"
      ENABLE_SOAP_LOGGING: ${enable_soap_logging}
      MONITORING_HEALTHCHECK_PORT: 9000
      MONITORING_HEALTHCHECK_PATH: healthcheck
      MONITORING_HEALTHCHECK_REFRESH_MS: 30000
      MONITORING_PROMETHEUS_PORT: 9001
    external_links:
      - ${kafka_service}:kafka
      - ${schema_registry_service}:schema-registry
    labels:
      prometheus.port: 9001
