version: '2'
services:
  source-ingest-pal:
    scale: 1
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 9000
      unhealthy_threshold: 3
      initializing_timeout: 120000
      interval: 30000
      strategy: recreate
      request_line: GET "/healthcheck" "HTTP/1.0"
      reinitializing_timeout: 120000
catalog:
  name: "ingest-pal"
  version: "1.0.3"
  description: "PAL Airline Surveilance Flights"
  minimum_rancher_version: v0.51.0
  upgrade_from: "<1.0.3"
  questions:
    - variable: application_id
      label: "Application Id"
      required: true
      type: "string"
      description: "An alphanumeric string that uniquely identifies this application instance. WARNING: Applications deployed with the same Application ID that consume data from the same Kafka topic will have data split between them. See the Kafka documentation for APPLICATION_ID for further explanation." 
    - variable: kafka_service         
      description: "Kafka Stack/Service."
      label: "Kafka Broker to Connect to."                             
      required: false
      type: "service"
    - variable: schema_registry_service
      description: "Confluent Schema Registry Service."
      label: "Schema Registry"
      required: false
      type: "service"
    - variable: kafka_host 
      label: "Kafka Broker"
      required: true
      type: "string"
      default: "kafka"
    - variable: kafka_port 
      label: "Kafka Broker Port"
      required: true
      type: "int"
      default: "9092"
    - variable: schema_registry_url                                                                                                      
      label: "Schema Registry URL"
      required: true
      type: "string"
      default: "http://schema-registry:8081"
      description: "URL to a Confluent Schema Registry"
    - variable: pal_endpoint
      label: "PAL Endpoint Name"
      required: true
      default: "palEndPoint"
      type: "string"
    - variable: pal_endpoint_address
      label: "PAL Endpoint URL"
      required: true
      default: "https://sis3.provair.com/RealtimeWebService/RealtimeService.svc"
      type: "string"
    - variable: pal_wsdl_address
      label: "PAL Endpoint WSDL URL"
      default: "https://sis3.provair.com/RealtimeWebService/RealtimeService.svc?wsdl"
      type: "string"
    - variable: pal_username
      label: "Username for PAL web service."
      required: true
      type: "string"
    - variable: pal_password
      label: "Password for PAL web service."
      required: true
      type: "password"
    - variable: kafka_output_topic
      label: "Kafka Output Topic (MaritimeContacts)"
      required: true
      type: "string"
    - variable: kafka_ais_output_topic
      label: "Kafka Output Topic (AIS)"
      required: true
      type: "string"
    - variable: kafka_edt_vessel_output_topic
      label: "Kafka Output Topic (EDT Vessel)"
      required: true
      type: "string"
    - variable: kafka_edt_animal_output_topic
      label: "Kafka Output Topic (EDT Animal)"
      required: true
      type: "string"
    - variable: kafka_edt_iceberg_output_topic
      label: "Kafka Output Topic (EDT Iceberg)"
      required: true
      type: "string"
    - variable: kafka_edt_packice_output_topic
      label: "Kafka Output Topic (EDT Packice)"
      required: true
      type: "string"
    - variable: kafka_edt_buoy_output_topic
      label: "Kafka Output Topic (EDT Buoy)"
      required: true
      type: "string"
    - variable: kafka_edt_gear_output_topic
      label: "Kafka Output Topic (EDT Gear)"
      required: true
      type: "string"
    - variable: kafka_edt_other_output_topic
      label: "Kafka Output Topic (EDT Other)"
      required: true
      type: "string"
    - variable: kafka_nav_other_output_topic
      label: "Kafka Output Topic (NAV)"
      required: true
      type: "string"
    - variable: kafka_gen_animal_output_topic
      label: "Kafka Output Topic (GEN Animal)"
      required: true
      type: "string"
    - variable: kafka_gen_iceberg_output_topic
      label: "Kafka Output Topic (GEN Iceberg)"
      required: true
      type: "string"
    - variable: kafka_gen_packice_output_topic
      label: "Kafka Output Topic (GEN Packice)"
      required: true
      type: "string"
    - variable: kafka_gen_buoy_output_topic
      label: "Kafka Output Topic (GEN Buoy)"
      required: true
      type: "string"
    - variable: kafka_gen_gear_output_topic
      label: "Kafka Output Topic (GEN Gear)"
      required: true
      type: "string"
    - variable: kafka_gen_other_output_topic
      label: "Kafka Output Topic (GEN Other)"
      required: true
      type: "string"
    - variable: enable_soap_logging
      label: "Enable the logging of SOAP request / responses."
      required: true
      type: "enum"
      default: "false"
      options:
        - "false"
        - "true"
    - variable: logging_level
      label: "The Log4J Logging Level"
      required: true
      type: "enum"
      options:
        - ALL
        - DEBUG
        - INFO
        - WARN
        - ERROR
        - FATAL
        - OFF
        - TRACE
      default: "INFO"
      description: "See Log4J documentation for further explanation of these levels."
    - variable: pal_cron_sched
      label: "Cron Schedule"
      required: true
      type: "string"
      default: "0 0/2 * * * ?"

