version: '2'
services:
  thumbor-image-server:
    scale: 1
    
catalog:
  name: "vessel image server"
  version: "1.0.0"
  description: "Provides vessel image over http"
  minimum_rancher_version: v0.51.0
  upgrade_from: none
  questions:
    - variable: application_id
      label: "Application Id"
      description: "An alphanumeric string that uniquely identifies this application instance."
      required: true
      type: "string"
      default: "Vessel-Image-Server"
    - variable: logging_level
      label: "Logging Level"
      description: "See Log4J documentation for further explanation of these levels."   
      required: true
      type: "enum"
      options:
        - all
        - debug
        - info
        - warn
        - error
        - fatal
        - trace
      default: "info"
    - variable: image_server_host
      label: "Image server host"         
      description: "Host on which image service running"                                   
      required: true
      type: "string"
      default: "0.0.0.0"
    - variable: image_server_port
      label: "Image server port"
      description: "Service access port"
      required: true
      type: "int"
      default: 8100