version: '2'
services:

  ingest-socket:
    image: 131.137.160.79:9191/gciplus-microservices/common/ingest-socket:4.2.1
    environment:
      APPLICATION_ID: ${application_id}-ingestsocket
      LOGGING_LEVEL: ${logging_level}
      INPUT_SOCKET_HOST: ${input_socket_host}
      INPUT_SOCKET_PORT: ${input_socket_port}
      INPUT_SOCKET_CLIENT_MODE_ENABLED: ${input_socket_client_mode_enabled}
      KAFKA_HOST: ${kafka_host}
      KAFKA_PORT: ${kafka_port} 
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic_rawacp128}
      MONITORING_HEALTHCHECK_INACTIVITY_TIMEOUT_MS: 300000
    external_links:
      - ${kafka_service}:kafka
    {{- if eq .Values.input_socket_client_mode_enabled "false" }}
    ports:
      - ${input_socket_port}:${input_socket_port}/tcp
    {{- end }}
    labels:
      prometheus.port: 9001
  
  decode-acp128:
    image: 131.137.160.79:9191/gciplus-microservices/gen3/decode-acp128:3.0.1
    environment:
      APPLICATION_ID: ${application_id}-decodeacp128
      AUTO_OFFSET_RESET: ${auto_offset_reset}
      BOOTSTRAP_SERVERS_CONFIG: ${kafka_host}:${kafka_port}
      KAFKA_INPUT_TOPICS: ${kafka_output_topic_rawacp128}
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic_avrorawotg}
      SCHEMA_REGISTRY_URL: ${schema_registry_url}
      ADDITIONAL_METADATA: Provider=${provider}
      NUM_STREAM_THREADS: ${num_stream_threads}
      LOGGING_LEVEL: ${logging_level}
    external_links:
      - ${kafka_service}:kafka
      - ${schema_registry_service}:schema-registry
    labels:
      prometheus.port: 9001
  
  decode-otg:
    image: 131.137.160.79:9191/gciplus-microservices/gen3/decode-otg:3.0.1
    environment:
      APPLICATION_ID: ${application_id}-decode-otg
      LOGGING_LEVEL: ${logging_level}
      NUM_STREAM_THREADS: ${num_stream_threads}
      AUTO_OFFSET_RESET: ${auto_offset_reset}
      BOOTSTRAP_SERVERS_CONFIG: ${kafka_host}:${kafka_port}
      SCHEMA_REGISTRY_URL: ${schema_registry_url}
      KAFKA_INPUT_TOPICS: ${kafka_output_topic_avrorawotg}
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic_avromaritimecontact}
      KAFKA_OUTPUT_FORMAT_SPECIFIC_TOPIC_CONTACTS: ${kafka_output_topic_avrootgmaritimecontact}
      KAFKA_OUTPUT_TOPIC_UNPARSABLE: ${kafka_output_topic_unparsable}
    external_links:
      - ${kafka_service}:kafka
      - ${schema_registry_service}:schema-registry
    labels:
      prometheus.port: 9001
