name: source-mssis-tv32
description: The ingest-mssis microservice accesses the volpe distributor service and downloads mssis ais data from the server.  It also uploads coastal ais data to the volpe distributor server.
version: latest
category: Ingester