version: '2'
services:
  maritimecontact-avro-to-json:
    image: 131.137.160.79:9191/gciplus-microservices/gen3/maritimecontact-avro-to-json:development
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}
      BOOTSTRAP_SERVERS_CONFIG: ${kafka_host}:${kafka_port}
      SCHEMA_REGISTRY_URL: ${schema_registry_url}
      KAFKA_INPUT_TOPICS: ${kafka_input_topics}
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic}
      NUM_STREAM_THREADS: ${num_stream_threads}
      AUTO_OFFSET_RESET: ${auto_offset_reset}
      MONITORING_HEALTHCHECK_PORT: 9000
      MONITORING_HEALTHCHECK_PATH: healthcheck
      MONITORING_HEALTHCHECK_REFRESH_MS: 30000
      MONITORING_PROMETHEUS_PORT: 9001
      LOGGING_LEVEL: ${logging_level}
      JAVA_OPTS: "-Xms64m -Xmx256m"
    external_links:
      - ${kafka_service}:kafka
      - ${schema_registry_service}:schema-registry
    labels:
      prometheus.port: 9001

  output-socket:
    image: 131.137.160.79:9191/gciplus-microservices/common/output-socket:3.0.0
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}-output-socket
      KAFKA_HOST: ${kafka_host}
      KAFKA_PORT: ${kafka_port}
      KAFKA_INPUT_TOPIC: ${kafka_output_topic}
      OUTPUT_SOCKET_HOST: ${output_socket_host}
      OUTPUT_SOCKET_PORT: ${output_socket_port}
      OUTPUT_SOCKET_DELAY: ${output_socket_delay}
      OUTPUT_SOCKET_DISCONNECT: ${output_socket_disconnect}
      OUTPUT_SOCKET_CLIENT_MODE_ENABLED: ${output_socket_client_mode_enabled}
      OUTPUT_SOCKET_PROTOCOL_UDP: ${output_socket_protocol_udp}
      OUTPUT_SOCKET_MULTICAST_OVER_UDP: ${output_socket_multicast_over_udp}
      AUTO_OFFSET_RESET: ${auto_offset_reset}
      MONITORING_HEALTHCHECK_PORT: 9000
      MONITORING_HEALTHCHECK_PATH: healthcheck
      MONITORING_HEALTHCHECK_REFRESH_MS: 30000
      SEDA_SIZE: 50000
      LOGGING_LEVEL: ${logging_level}
      JAVA_OPTS: "-Xms512m -Xmx1g -Dlog4j.configurationFile=log4j2.properties -javaagent:lib/jmx_prometheus_javaagent-0.10.jar=9001:config.yml"
    external_links:
      - ${kafka_service}:kafka
    labels:
      prometheus.port: 9001