version: '2'
services:
  source-ingest-lrit:
    scale: 1
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 9000
      unhealthy_threshold: 3
      initializing_timeout: 120000
      interval: 30000
      strategy: recreate
      request_line: GET "/healthcheck" "HTTP/1.0"
      reinitializing_timeout: 120000
  lrit-redis:
    scale: 1

catalog:
  name: "ingest-lrit"
  version: "development"
  description: "The ingest LRIT microservice polls the LRIT web service at certain time intervals sending it a request for ship data to process into MaritimeContacts and LritMaritimeContacts."
  minimum_rancher_version: v0.51.0
  upgrade_from: none
  questions:
    - variable: application_id
      label: "Application Id"
      required: true
      type: "string"
      description: "An alphanumeric string that uniquely identifies this application instance. WARNING: Applications deployed with the same Application ID that consume data from the same Kafka topic will have data split between them. See the Kafka documentation for APPLICATION_ID for further explanation." 
    - variable: kafka_service         
      description: "Kafka Stack/Service."
      label: "Kafka Broker to Connect to."                             
      required: false
      type: "service"
    - variable: schema_registry_service
      description: "Confluent Schema Registry Service."
      label: "Schema Registry"
      required: false
      type: "service"
    - variable: kafka_host 
      label: "Kafka Broker"
      required: true
      type: "string"
      default: "kafka"
    - variable: kafka_port 
      label: "Kafka Broker Port"
      required: true
      type: "int"
      default: "9092"
    - variable: schema_registry_url                                                                                                      
      label: "Schema Registry URL"
      required: true
      type: "string"
      default: "http://schema-registry:8081"
      description: "URL to a Confluent Schema Registry"
    - variable: kafka_host 
      label: "Kafka Broker"
      required: true
      type: "string"
      default: "kafka"
    - variable: kafka_port 
      label: "Kafka Broker Port"
      required: true
      type: "int"
      default: "9092"
    - variable: lrit_endpoint
      label: "LRIT Endpoint Name"
      required: true
      default: "lritEndPoint"
      type: "string"
    - variable: lrit_endpoint_address
      label: "LRIT Endpoint URL"
      required: true
      default: "https://can-service.lrit.com/DCCommandService"
      type: "string"
    - variable: lrit_wsdl_address
      label: "LRIT Endpoint WSDL URL"
      default: "https://can-service.lrit.com/DCCommandService?WSDL"
      type: "string"
    - variable: lrit_username
      label: "Username for LRIT web service."
      required: true
      type: "string"
    - variable: lrit_password
      label: "Password for LRIT web service."
      required: true
      type: "password"
    - variable: kafka_output_topic
      label: "Name of topic where MaritimeContact messages are stored on the kafka broker"
      required: true
      type: "string"
    - variable: kafka_lrit_maritime_contact_home_output
      label: "Name of topic where LritMaritimeContact home messages are stored on the kafka broker"
      required: true
      type: "string"
    - variable: kafka_lrit_maritime_contact_foreign_output
      label: "Name of topic where LritMaritimeContact foreign messages are stored on the kafka broker"
      required: true
      type: "string"
    - variable: enable_soap_logging
      label: "Enable the logging of SOAP request / responses."
      required: true
      type: "enum"
      default: "false"
      options:
        - "false"
        - "true"
    - variable: logging_level
      label: "The Log4J Logging Level"
      required: true
      type: "enum"
      options:
        - ALL
        - DEBUG
        - INFO
        - WARN
        - ERROR
        - FATAL
        - OFF
        - TRACE
      default: "INFO"
      description: "See Log4J documentation for further explanation of these levels."
    - variable: cron_schedule
      label: "Cron Schedule"
      required: true
      type: "string"
      default: "0 0/2 * * * ?"
