version: '2'

services:

  output-socket:
    image: 131.137.160.79:9191/gciplus-microservices/common/output-socket:3.2.0
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}
      KAFKA_HOST: ${kafka_host}
      KAFKA_PORT: ${kafka_port}
      KAFKA_INPUT_TOPIC: ${kafka_input_topic}
      OUTPUT_SOCKET_HOST: ${output_socket_host}
      OUTPUT_SOCKET_PORT: ${output_socket_port}
      OUTPUT_SOCKET_DELAY: ${output_socket_delay}
      OUTPUT_SOCKET_DISCONNECT: ${output_socket_disconnect}
      OUTPUT_SOCKET_CLIENT_MODE_ENABLED: ${output_socket_client_mode_enabled}
      OUTPUT_SOCKET_PROTOCOL_UDP: ${output_socket_protocol_udp}
      OUTPUT_SOCKET_MULTICAST_OVER_UDP: ${output_socket_multicast_over_udp}
      AUTO_OFFSET_RESET: ${auto_offset_reset}
      LOGGING_LEVEL: ${logging_level}
    external_links:
      - ${kafka_service}:kafka
    labels:
      prometheus.port: 9001
