version: '2'
services:

  msoc-rest-webservice:
    image: 131.137.160.79:9191/gciplus-microservices/gen3/msoc-rest-webservice:development
    restart: on-failure
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      MONGODB_MSOC_DB: msoc
    links:
      - mongodb:mongodb
    ports:
      - ${webservice_port}:80/tcp

  msoc-geodecimator:
    image: 131.137.160.79:9191/gciplus-microservices/gen3/maritimecontact-geodecimator:development
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}-decimator
      BOOTSTRAP_SERVERS_CONFIG: ${bootstap_servers_config} 
      SCHEMA_REGISTRY_URL: ${schema_registry_url}
      KAFKA_INPUT_TOPICS: ${kafka_input_topics}
      KAFKA_OUTPUT_TOPIC: ${kafka_output_topic}
      GEODECIMATOR_WINDOW_MS: ${geodecimator_window_ms}
      GEODECIMATOR_EXPIRY_MS: ${geodecimator_expiry_ms}
      GEODECIMATOR_POLYGON: ${geodecimator_polygon}
      GEODECIMATOR_AGGREGATION_FIELDS: "Name,Mmsi,Imo,Callsign,Metadata.Provider,Provider"
      GEODECIMATOR_GEOHASH_LENGTH: 3
      NUM_STREAM_THREADS: ${num_stream_threads}
      NUM_SEGMENTS: 20
      AUTO_OFFSET_RESET: ${auto_offset_reset}
      FUTURE_CONTACT_TOLERANCE_MS: 600000
      MONITORING_HEALTHCHECK_PORT: 9000
      MONITORING_HEALTHCHECK_PATH: healthcheck
      MONITORING_HEALTHCHECK_REFRESH_MS: 30000
      MONITORING_PROMETHEUS_PORT: 9001
      LOGGING_LEVEL: ${logging_level}
      JAVA_OPTS: "-Xms512m -Xmx1g"
    external_links:
      - ${kafka_service}:kafka
      - ${schema_registry_service}:schema-registry
    labels:
      prometheus.port: 9001

  msoc-processor:
    image: 131.137.160.79:9191/gciplus-microservices/gen3/maritimecontact-msoc-processor:development
    restart: on-failure
    environment:
      APPLICATION_ID: ${application_id}-processor
      AUTO_OFFSET_RESET: ${auto_offset_reset}
      NUM_STREAM_THREADS: ${num_stream_threads}
      BOOTSTRAP_SERVERS_CONFIG: ${bootstap_servers_config}
      MSOC_ENTITY_FIELDS: Name,Mmsi,Imo,Callsign,EntityType,Category,Flag
      MONGODB_URI: mongodb://mongodb:27017
      MSOC_DB: msoc
      MSOC_ENTITIES_COLLECTION: msoc_entities
      MSOC_CONTACTS_COLLECTION: msoc_contacts
      MSOC_COUNTERS_COLLECTION: msoc_counters
      KAFKA_INPUT_TOPICS: ${kafka_output_topic}
      LOGGING_LEVEL: INFO
      SCHEMA_REGISTRY_URL: ${schema_registry_url}
      JAVA_OPTS: -Xms512m -Xmx1g
    external_links:
      - ${kafka_service}:kafka
      - ${schema_registry_service}:schema-registry
    links:
      - mongodb:mongodb
    labels:
      prometheus.port: 9001

  mongodb:
    image: mongo:latest
    restart: on-failure
    command: ["--wiredTigerCacheSizeGB", "2"]
